### ISSUE TITLE
[Feature Request]Please upload the videos

### ISSUE THREAD

**Issue by kusurin** [MaureenAscona/DLC-MotoRater#1]
**Problem Related with the Feature Request**
Google drive of MotoRater currently lacks the videos file that is referenced in the paper, whereas MotorBox includes them. 

**Solution Expected**
Could you please upload the original videos that associated with MotoRater?

**Comment by MaureenAscona** [comment]
Hello @kusurin, thank you for highlighting this issue! I didn't notice these files were missing. They have now been added to the Google Drive. Thank you!
